name: Android CI

on:
  pull_request:
    branches:
      - main  # Run on pull requests targeting the 'main' branch
  push:
    branches:
      - main  # Run on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: '24'  # Android 7.0 (API 24)
          target: android-24  # Specify the target SDK version - here Android 14.0
          script: true  # Ensures SDK is installed

      # Step 4: Build the project
      - name: Build with Gradle
        run: ./gradlew build  # or `./gradlew assembleDebug` if you want to build a specific variant

      # Step 5: Run tests
      - name: Run tests
        run: ./gradlew test

      # Step 6: Run lint checks (optional)
      - name: Run Lint
        run: ./gradlew lint  # Optional step for running lint checks
